version: "3.7"

services:
  app:
    build: ./dockerfiles/books
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_service
    ports:
      - '33061:3306'
    restart: always
