---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 4
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: books
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
