---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
